name: sohal_kutuphane
description: LibSohal Library Software
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flex_color_scheme: ^5.0.1
  searchbar_animation: ^0.0.2
  skeleton_animation: ^0.1.4
  carousel_slider: ^4.0.0
  numeric_keyboard: ^1.1.0
  progress_state_button: ^1.0.4
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.4+5
  syncfusion_flutter_charts: ^20.1.48
  hive_flutter: ^1.1.0
  visibility_aware_state: ^1.0.3
  path_provider: ^2.0.9
  lottie: ^1.3.0
  flag: ^6.0.0
  flutter_animated_button: ^2.0.0
  introduction_screen: ^3.0.2
  animated_text_kit: ^4.2.1
  fsearch: ^1.0.1
  delayed_display: ^2.0.0
  cached_network_image: ^3.2.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.2
  universal_html: ^2.0.8
  ai_barcode: ^3.0.1
  #camera: ^0.9.5+1
  #flutter_mobile_vision_2: ^0.1.13
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_launcher_icons:

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/images/
      - assets/objects/
      - assets/objects/Book Textures/


  fonts:
    - family: mint
      fonts:
        - asset: assets/fonts/mint.otf
  #       - asset: fonts/Schyler-Italic.ttf


